"""
agents/kernel_generation_agent.py
-----------------------------------
Kernel Generation Agent — Stage 4, Part 2.

Given a KernelResearchReport and BottleneckAnalysis, generates a complete,
hardware-optimised Triton (or CUDA C++) kernel targeting the identified bottleneck.

The generated kernel is saved to kernels/generated/<session_id>/<kernel_name>.py
and can be loaded by vLLM via monkey-patch or standalone microbenchmark.

Architecture-specific optimisations the LLM is instructed to use:

NVIDIA H100/A100:
  - TMA (Tensor Memory Accelerator) for async tile loading (H100 only)
  - cp.async for double-buffered GMEM→SMEM pipeline
  - Warp specialization: producer/consumer warp groups
  - wmma / mma.sync for Tensor Core instructions
  - Register tiling: careful BLOCK_M/BLOCK_N/BLOCK_K selection
  - Split-K for batch-size=1 decode (small-M GEMM)

AMD MI300X:
  - Direct-to-LDS (DL) load paths
  - MFMA instruction selection (f16, bf16, fp8)
  - Wavefront-level tiling
  - LDS padding to avoid bank conflicts (stride 128 bytes)
  - ROCm Triton backend specifics (triton-rocm)

For attention kernels:
  - Online softmax (Dao/FlashAttention algorithm)
  - Causal/non-causal mask fusion
  - GQA: head group interleaving
  - Paged KV cache: block pointer arithmetic
  - Prefill vs decode kernel split

Usage
-----
    generator = KernelGenerationAgent(do_client=client)
    kernel = await generator.generate(
        research=kernel_research_report,
        bottleneck=bottleneck_analysis,
        model_id="Qwen/Qwen2.5-7B-Instruct",
        gpu_type="H100",
        session_id="...",
    )
    print(kernel.file_path)   # path to generated .py file
    print(kernel.triton_code) # full Triton kernel code
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from agents.bottleneck_reasoning_agent import BottleneckAnalysis
from agents.do_client import DOClient, DOClientError
from agents.kernel_research_agent import KernelResearchReport

log = logging.getLogger("agents.kernel_generation_agent")

_REPO_ROOT = Path(__file__).resolve().parent.parent
_KERNELS_DIR = _REPO_ROOT / "kernels" / "generated"


# ---------------------------------------------------------------------------
# Generated kernel dataclass
# ---------------------------------------------------------------------------

@dataclass
class GeneratedKernel:
    """A GPU kernel generated by the Kernel Generation Agent."""
    session_id: str
    kernel_name: str
    target_op: str                  # attention | gemm | moe | rmsnorm | rope
    gpu_type: str
    model_id: str

    # Source code
    triton_code: str = ""           # Full Triton Python file contents
    cuda_code: str = ""             # CUDA C++ if applicable (empty for Triton-only)

    # File paths
    file_path: str = ""             # Path to the .py file
    cuda_file_path: str = ""        # Path to .cu file if generated

    # Metadata
    tile_config: Dict[str, int] = field(default_factory=dict)
    expected_speedup_pct: float = 0.0
    algorithm: str = ""             # "flash_attention_v2_causal_gqa" etc.

    # Generation status
    success: bool = False
    error: str = ""

    # Whether this kernel is a replacement for an existing vLLM kernel
    replaces_vllm_kernel: bool = False
    vllm_integration_notes: str = ""

    def load_code(self) -> str:
        """Read kernel code from file (in case it was modified after generation)."""
        if self.file_path and Path(self.file_path).exists():
            return Path(self.file_path).read_text()
        return self.triton_code


# ---------------------------------------------------------------------------
# System prompts
# ---------------------------------------------------------------------------

_TRITON_GENERATION_SYSTEM_PROMPT = """\
You are a world-class GPU kernel engineer with deep expertise in Triton, CUDA, and ROCm.
You write production-quality, fully functional GPU kernels optimized for LLM inference.

You will receive:
  - A bottleneck analysis identifying the target kernel to optimize
  - Research report with the algorithmic approach to use
  - Hardware specifications (GPU type, memory hierarchy)
  - Model architecture parameters (num_heads, head_dim, num_kv_heads, etc.)
  - The optimization approach (flash attention, paged attention, grouped GEMM, etc.)

Your task: generate a COMPLETE, RUNNABLE Triton kernel file that:

1. Implements the specified optimization algorithm correctly
2. Uses hardware-specific optimizations:
   - For H100: `tl.load` with `.cache_modifier = ".ca"`, TMA-like prefetching via
     `tl.extra.cuda.experimental_device_tensormap_create2d` when applicable
   - For all NVIDIA: `tl.dot` mapped to mma.sync (Tensor Core), explicit
     `BLOCK_M`/`BLOCK_N`/`BLOCK_K` tuning for peak utilization
   - For AMD: ROCm-compatible Triton ops, `tl.dot` maps to MFMA, LDS padding
3. Includes an `@triton.autotune` decorator with configs for the target hardware
4. Includes a Python wrapper function with the same interface as the target vLLM function
5. Includes a correctness test that runs against a PyTorch reference
6. Includes a microbenchmark that reports throughput and efficiency

## Code structure required:
```python
# kernels/generated/<session_id>/<kernel_name>.py
# OceanTune AI — Generated Kernel
# Target: <operation type>
# GPU: <gpu_type>
# Algorithm: <algorithm name>

import triton
import triton.language as tl
import torch
from typing import Optional

# ─── Autotuning configurations ───────────────────────────────────────────────
@triton.autotune(configs=[...], key=[...])
@triton.jit
def <kernel_name>(...):
    # ... kernel body

# ─── Python wrapper ───────────────────────────────────────────────────────────
def <op_name>(...) -> torch.Tensor:
    # ... wrapper with grid calculation

# ─── Correctness test ─────────────────────────────────────────────────────────
def test_correctness():
    # ... compare against torch reference, assert max_abs_err < threshold

# ─── Microbenchmark ───────────────────────────────────────────────────────────
def benchmark(batch_size=1, seq_len=2048, ...):
    import json
    # ... timed run, print JSON with throughput and efficiency

if __name__ == "__main__":
    test_correctness()
    benchmark()
```

## Critical correctness requirements:
- Attention: causal mask must be applied correctly (never attend to future tokens)
- Numerics: online softmax MUST maintain numerical stability (subtract max before exp)
- GQA: key/value head groups must be broadcast correctly
- Paged KV: block pointer arithmetic must handle variable sequence lengths
- RMSNorm: eps prevents division by zero

## Performance requirements:
- Use `tl.constexpr` for compile-time constants (BLOCK_M, BLOCK_N, HEAD_DIM, etc.)
- Minimize global memory accesses — use shared memory / registers for reuse
- For attention: Q/K/V tiles should fit in SRAM: SRAM_SIZE / (3 * BLOCK * HEAD_DIM * 2bytes)

Respond with ONLY the Python code — no explanation text outside the code.
Begin with `# kernels/generated/` and end with the `if __name__ == "__main__":` block.
"""

_CUDA_GENERATION_SYSTEM_PROMPT = """\
You are an expert CUDA C++ kernel engineer specializing in LLM inference optimization.
Generate a complete CUDA kernel for the specified operation.

Requirements:
  1. Full .cu file with kernel + wrapper (callable from Python via ctypes or torch.ops)
  2. Hardware-specific: use __mma_sync / wmma for Tensor Cores, TMA for H100
  3. Shared memory tiling with double buffering via cp.async
  4. Warp specialization where applicable
  5. A test main() that validates correctness against a reference

Output ONLY valid CUDA C++ code. Begin with `// kernels/generated/` comment.
"""


class KernelGenerationAgent:
    """
    Generates hardware-optimized GPU kernels based on research findings.
    """

    def __init__(self, do_client: DOClient) -> None:
        self._client = do_client

    async def generate(
        self,
        *,
        research: KernelResearchReport,
        bottleneck: BottleneckAnalysis,
        model_id: str,
        gpu_type: str,
        session_id: str,
        model_meta: Optional[Dict[str, Any]] = None,
        generate_cuda: bool = False,
    ) -> GeneratedKernel:
        """
        Generate an optimized kernel for the bottleneck operation.

        Parameters
        ----------
        research : KernelResearchReport
            Research findings from KernelResearchAgent.
        bottleneck : BottleneckAnalysis
            The classified bottleneck.
        model_id : str
        gpu_type : str
        session_id : str
        model_meta : dict
            Model architecture (num_heads, head_dim, etc.)
        generate_cuda : bool
            Also generate CUDA C++ alongside Triton (for comparison/fallback).

        Returns
        -------
        GeneratedKernel with file_path pointing to the written kernel.
        """
        target_op = bottleneck.primary_component or research.target_kernel or "attention"
        kernel_name = f"oceantune_{target_op}_{gpu_type.lower().replace('-', '_')}"

        kernel = GeneratedKernel(
            session_id=session_id,
            kernel_name=kernel_name,
            target_op=target_op,
            gpu_type=gpu_type,
            model_id=model_id,
        )

        if research.top_approach:
            kernel.expected_speedup_pct = research.top_approach.expected_speedup_pct
            kernel.tile_config = research.top_approach.tile_config
            kernel.algorithm = research.top_approach.title

        log.info(
            "KernelGenerationAgent: generating %s kernel for %s on %s",
            target_op, model_id, gpu_type,
        )

        user_msg = self._build_generation_prompt(
            research=research,
            bottleneck=bottleneck,
            kernel_name=kernel_name,
            target_op=target_op,
            model_id=model_id,
            gpu_type=gpu_type,
            model_meta=model_meta or {},
        )

        try:
            # Generate Triton kernel
            triton_code = await self._client.chat(
                messages=[{"role": "user", "content": user_msg}],
                system=_TRITON_GENERATION_SYSTEM_PROMPT,
                json_mode=False,  # Plain code output
            )

            # Strip any markdown fences
            triton_code = _strip_code_fences(triton_code)
            kernel.triton_code = triton_code

            # Write to disk
            kernel_dir = _KERNELS_DIR / session_id
            kernel_dir.mkdir(parents=True, exist_ok=True)
            kernel_path = kernel_dir / f"{kernel_name}.py"
            kernel_path.write_text(triton_code, encoding="utf-8")
            kernel.file_path = str(kernel_path)
            kernel.success = True

            log.info("KernelGenerationAgent: wrote %d lines to %s",
                     len(triton_code.splitlines()), kernel_path)

            # Optionally generate CUDA C++ as well
            if generate_cuda:
                cuda_code = await self._generate_cuda(
                    research=research,
                    bottleneck=bottleneck,
                    kernel_name=kernel_name,
                    model_id=model_id,
                    gpu_type=gpu_type,
                    model_meta=model_meta or {},
                )
                if cuda_code:
                    cuda_path = kernel_dir / f"{kernel_name}.cu"
                    cuda_path.write_text(cuda_code, encoding="utf-8")
                    kernel.cuda_code = cuda_code
                    kernel.cuda_file_path = str(cuda_path)

        except (DOClientError, Exception) as exc:
            log.warning("KernelGenerationAgent LLM call failed: %s", exc)
            kernel.error = str(exc)
            # Write a skeleton kernel as fallback
            kernel.triton_code = self._generate_skeleton(target_op, gpu_type, model_meta or {})
            kernel_dir = _KERNELS_DIR / session_id
            kernel_dir.mkdir(parents=True, exist_ok=True)
            kernel_path = kernel_dir / f"{kernel_name}_skeleton.py"
            kernel_path.write_text(kernel.triton_code, encoding="utf-8")
            kernel.file_path = str(kernel_path)
            kernel.success = False

        return kernel

    def _build_generation_prompt(
        self,
        *,
        research: KernelResearchReport,
        bottleneck: BottleneckAnalysis,
        kernel_name: str,
        target_op: str,
        model_id: str,
        gpu_type: str,
        model_meta: Dict[str, Any],
    ) -> str:
        vendor = "amd" if gpu_type in {"MI300X", "MI325X", "MI350X"} else "nvidia"
        top = research.top_approach

        sections = [
            f"# Kernel to generate: {kernel_name}",
            f"# Target operation: {target_op}",
            f"# Model: {model_id}",
            f"# GPU: {gpu_type} (vendor={vendor})",
            "",
            "## Research findings",
        ]

        if top:
            sections.extend([
                f"Algorithm: {top.title}",
                f"Approach type: {top.approach_type}",
                f"Expected speedup: {top.expected_speedup_pct:.0f}%",
                f"Evidence: {top.evidence}",
                f"Algorithm description: {top.triton_approach or '(use standard algorithm)'}",
                f"Tile config: {json.dumps(top.tile_config) if top.tile_config else 'autotuned'}",
            ])
            if vendor == "nvidia":
                sections.append(f"NVIDIA notes: {top.nvidia_notes or 'standard CUDA/Triton'}")
            else:
                sections.append(f"AMD notes: {top.amd_notes or 'standard ROCm Triton'}")

        sections.append("")
        sections.append("## Bottleneck context")
        sections.append(f"Primary bottleneck class: {bottleneck.primary_bottleneck}")
        sections.append(f"Roofline bound: {bottleneck.roofline_bound}")
        sections.append(f"Arithmetic intensity: {bottleneck.arithmetic_intensity:.1f} FLOP/byte")

        if model_meta:
            sections.append("")
            sections.append("## Model architecture")
            sections.append(json.dumps(model_meta, indent=2))

        sections.append("")
        sections.append(f"## Diagnostic questions from bottleneck analyst")
        for q in bottleneck.diagnostic_questions[:3]:
            sections.append(f"  - {q}")

        sections.append("")
        sections.append("Generate the complete Triton kernel file for this operation.")

        return "\n".join(sections)

    async def _generate_cuda(
        self,
        *,
        research: KernelResearchReport,
        bottleneck: BottleneckAnalysis,
        kernel_name: str,
        model_id: str,
        gpu_type: str,
        model_meta: Dict[str, Any],
    ) -> str:
        """Optionally generate a CUDA C++ companion kernel."""
        user_msg = (
            f"Generate a CUDA C++ kernel implementing: {research.generation_priority}\n"
            f"Kernel name: {kernel_name}\n"
            f"GPU: {gpu_type}\n"
            f"Model: {model_id}\n"
            f"Architecture: {json.dumps(model_meta, indent=2)}\n"
            f"Use wmma/mma.sync for Tensor Cores, cp.async for async GMEM→SMEM."
        )
        try:
            code = await self._client.chat(
                messages=[{"role": "user", "content": user_msg}],
                system=_CUDA_GENERATION_SYSTEM_PROMPT,
                json_mode=False,
            )
            return _strip_code_fences(code)
        except Exception as exc:
            log.warning("CUDA generation failed: %s", exc)
            return ""

    def _generate_skeleton(
        self,
        target_op: str,
        gpu_type: str,
        model_meta: Dict[str, Any],
    ) -> str:
        """Fallback: generate a minimal skeleton for manual completion."""
        nheads = model_meta.get("num_heads", 32)
        head_dim = model_meta.get("head_dim", 128)
        return f"""\
# OceanTune AI — Generated Kernel Skeleton
# Target: {target_op}
# GPU: {gpu_type}
# NOTE: LLM generation failed — this is a skeleton for manual completion

import triton
import triton.language as tl
import torch

# ─── Autotuning configurations ───────────────────────────────────────────────
@triton.autotune(
    configs=[
        triton.Config({{"BLOCK_M": 128, "BLOCK_N": 64, "BLOCK_K": 64}}, num_stages=3, num_warps=8),
        triton.Config({{"BLOCK_M": 64, "BLOCK_N": 64, "BLOCK_K": 64}}, num_stages=4, num_warps=4),
        triton.Config({{"BLOCK_M": 128, "BLOCK_N": 128, "BLOCK_K": 32}}, num_stages=2, num_warps=8),
    ],
    key=["SEQ_LEN", "NUM_HEADS", "HEAD_DIM"],
)
@triton.jit
def {target_op}_kernel(
    # TODO: Add kernel arguments
    SEQ_LEN: tl.constexpr,
    NUM_HEADS: tl.constexpr = {nheads},
    HEAD_DIM: tl.constexpr = {head_dim},
    BLOCK_M: tl.constexpr = 128,
    BLOCK_N: tl.constexpr = 64,
    BLOCK_K: tl.constexpr = 64,
):
    # TODO: Implement {target_op} kernel
    pass


def {target_op}(*args, **kwargs):
    # TODO: Implement Python wrapper
    raise NotImplementedError("Kernel skeleton — needs implementation")


def test_correctness():
    # TODO: Add correctness test
    print("No correctness test implemented yet")


def benchmark():
    # TODO: Add benchmark
    import json
    print(json.dumps({{"mean_us": 0, "p50_us": 0, "tflops": 0}}))


if __name__ == "__main__":
    test_correctness()
    benchmark()
"""


def _strip_code_fences(text: str) -> str:
    """Remove ```python ... ``` or ``` ... ``` fences from LLM output."""
    # Strip markdown fences
    text = re.sub(r"^```(?:python|cuda|cpp)?\s*\n", "", text, flags=re.MULTILINE)
    text = re.sub(r"\n```\s*$", "", text, flags=re.MULTILINE)
    # Remove any leading "Here is the kernel:" type text before the first import
    match = re.search(r"^#\s*kernels/", text, re.MULTILINE)
    if match:
        text = text[match.start():]
    elif "import triton" in text:
        idx = text.index("import triton")
        # Keep any top-level comments before it
        comment_start = text.rfind("#", 0, idx)
        if comment_start >= 0 and "\n" not in text[comment_start:idx]:
            text = text[comment_start:]
        else:
            text = text[idx:]
    return text.strip()
